### ISSUE TITLE
Game crashes when joining

### ISSUE THREAD

**Issue by terrarier2111** [Lea-fish/Leafish#87]
When rejoining the same server, you were on before, sometimes this happens:
```
[main.rs:104][INFO] Detected server protocol version 340
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/render/hud.rs:730:18
stack backtrace:
   0:     0x55d9213435b0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d9213435b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d9213435b0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d9213435b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d92136792c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x55d92133c5e5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x55d9213456eb - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d9213456eb - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d9213456eb - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x55d9213451c1 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x55d921345db4 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x55d921345867 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x55d921343aac - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d9213457f9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x55d920ac97b1 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x55d920ac96fd - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x55d920b320cf - leafish::render::hud::Hud::render_slots_items::h6bcf02f61a0c024b
  17:     0x55d920b2d3d1 - <leafish::render::hud::Hud as leafish::screen::Screen>::on_active::hd6da8aeafb84da42
  18:     0x55d920b4ef73 - leafish::screen::ScreenSystem::tick::h08f06ad5aa2eb9bc
  19:     0x55d920b892c2 - leafish::tick_all::h00235484dd755d17
  20:     0x55d920b88436 - leafish::main::{{closure}}::h1659320657fe8a3a
  21:     0x55d920ae1060 - winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run::h86c292fdf5926440
  22:     0x55d920b76d98 - winit::platform_impl::platform::EventLoop<T>::run::hc65eee72f1807c06
  23:     0x55d920b76d0c - winit::event_loop::EventLoop<T>::run::hc62e00f4417c1251
  24:     0x55d920b87d2d - leafish::main::h97830021eee567fc
  25:     0x55d920b5e6c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h08d9360cab6cc87a
  26:     0x55d920c420a9 - std::rt::lang_start::{{closure}}::h6a3b46ca54cce1ec
  27:     0x55d9213463b9 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  28:     0x55d9213463b9 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  29:     0x55d9213463b9 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  30:     0x55d9213463b9 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  31:     0x55d9213463b9 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  32:     0x55d920b8c0d2 - main
  33:     0x7f9430490b75 - __libc_start_main
  34:     0x55d920ac9f8e - _start
  35:                0x0 - <unknown>

Process finished with exit code 101
```

**Comment by terrarier2111** [comment]
This seems to be quite outdated, so i'll close this for now.
